a = input('digite algo: ')
print('É numerico: ', a.isnumeric())
print('É alfabetico: ', a.isalpha())
print('É com letras maiusculas: ', a.isupper())
print('É com letras minusculas: ', a.islower())
print('É alfanumerico: ', a.isalnum())
print('É composto de espaços:', a.isspace())
print('É um numero decimal: ', a.isdecimal())
print('É capitalizada(maiusculas e minusculas):', a.istitle())
print('É apenas digitos(numeros)', a.isdigit())
print('', a.isidentifier())
print('É imprimivel: ', a.isprintable())